<?xml version="1.0"?>
<!--
Implementation by the Keccak, Keyak and Ketje Teams, namely, Guido Bertoni,
Joan Daemen, Michaël Peeters, Gilles Van Assche and Ronny Van Keer, hereby
denoted as "the implementer".

For more information, feedback or questions, please refer to our websites:
http://keccak.noekeon.org/
http://keyak.noekeon.org/
http://ketje.noekeon.org/

To the extent possible under law, the implementer has waived all copyright
and related or neighboring rights to the source code in this file.
http://creativecommons.org/publicdomain/zero/1.0/
-->
<build>
    <fragment name="common">
        <h>Common/brg_endian.h</h>
    </fragment>

    <fragment name="keccak" inherits="common">
        <c>Constructions/KeccakDuplex.c</c>
        <c>Constructions/KeccakSponge.c</c>
        <c>Modes/KeccakHash.c</c>
        <c>Tests/genKAT.c</c>
        <c>Tests/main.c</c>
        <c>Tests/testDuplex.c</c>
        <c>Tests/testSnP.c</c>
        <c>Tests/testSponge.c</c>
        <h>Constructions/KeccakDuplex.h</h>
        <h>Constructions/KeccakSponge.h</h>
        <h>Modes/KeccakHash.h</h>
        <h>Tests/genKAT.h</h>
        <h>Tests/testDuplex.h</h>
        <h>Tests/testSnP.h</h>
        <h>Tests/testSponge.h</h>
    </fragment>

    <fragment name="optimized">
        <c>Tests/timing.c</c>
        <h>Common/brg_endian.h</h>
        <h>Tests/timing.h</h>
        <gcc>-fomit-frame-pointer</gcc>
        <gcc>-O3</gcc>
        <gcc>-g0</gcc>
        <gcc>-march=native</gcc>
        <gcc>-mtune=native</gcc>
    </fragment>

    <!-- Keccak[r+c=1600] -->

    <fragment name="width1600">
        <h>KeccakF-1600/KeccakF-1600-interface.h</h>
    </fragment>

    <fragment name="reference1600" inherits="common width1600">
        <c>KeccakF-1600/Reference/KeccakF-1600-reference.c</c>
        <c>SnP/SnP-FBWL-default.c</c>
        <c>Tests/displayIntermediateValues.c</c>
        <h>KeccakF-1600/Reference/KeccakF-reference.h</h>
        <h>KeccakF-1600/Reference/SnP-interface.h</h>
        <h>SnP/SnP-FBWL-default.h</h>
        <h>Tests/displayIntermediateValues.h</h>
        <gcc>-DKeccakReference</gcc>
        <gcc>-O</gcc>
    </fragment>

    <fragment name="reference32BI" inherits="width1600">
        <c>KeccakF-1600/Reference/KeccakF-1600-reference32BI.c</c>
        <c>SnP/SnP-FBWL-default.c</c>
        <c>Tests/displayIntermediateValues.c</c>
        <h>KeccakF-1600/Reference/KeccakF-reference.h</h>
        <h>KeccakF-1600/Reference/SnP-interface.h</h>
        <h>SnP/SnP-FBWL-default.h</h>
        <h>Tests/displayIntermediateValues.h</h>
        <gcc>-O</gcc>
        <gcc>-DKeccakReference</gcc>
        <gcc>-DKeccakReference32BI</gcc>
    </fragment>

    <fragment name="optimized64" inherits="width1600 optimized">
        <c>KeccakF-1600/Optimized64/KeccakF-1600-opt64.c</c>
        <c>SnP/SnP-FBWL-default.c</c>
        <h>KeccakF-1600/Optimized64/KeccakF-1600-opt64-settings.h</h>
        <h>KeccakF-1600/Optimized/KeccakF-1600-unrolling.macros</h>
        <h>KeccakF-1600/Optimized64/KeccakF-1600-64.macros</h>
        <h>KeccakF-1600/Optimized64/SnP-interface.h</h>
        <h>SnP/SnP-FBWL-default.h</h>
        <h>SnP/SnP-Relaned.h</h>
        <gcc>-m64</gcc>
    </fragment>

    <fragment name="inplace32BI" inherits="width1600 optimized">
        <c>KeccakF-1600/Inplace32BI/KeccakF-1600-inplace32BI.c</c>
        <c>SnP/SnP-FBWL-default.c</c>
        <h>KeccakF-1600/Inplace32BI/SnP-interface.h</h>
        <h>SnP/SnP-FBWL-default.h</h>
        <h>SnP/SnP-Relaned.h</h>
    </fragment>

    <fragment name="compact64" inherits="width1600 optimized">
        <c>KeccakF-1600/Compact64/Keccak-compact64.c</c>
        <c>SnP/SnP-FBWL-default.c</c>
        <h>KeccakF-1600/Compact64/SnP-interface.h</h>
        <h>SnP/SnP-FBWL-default.h</h>
        <h>SnP/SnP-Relaned.h</h>
        <gcc>-m64</gcc>
    </fragment>

    <fragment name="asmx86-64-common" inherits="width1600 optimized">
        <c>SnP/SnP-FBWL-default.c</c>
        <h>KeccakF-1600/OptimizedAsmX86-64/SnP-interface.h</h>
        <h>SnP/SnP-FBWL-default.h</h>
        <gcc>-m64</gcc>
    </fragment>

    <fragment name="asmx86-64" inherits="asmx86-64-common">
        <c>KeccakF-1600/OptimizedAsmX86-64/KeccakF-1600-x86-64-gas.s</c>
    </fragment>

    <fragment name="asmx86-64-shld" inherits="asmx86-64-common">
        <c>KeccakF-1600/OptimizedAsmX86-64/KeccakF-1600-x86-64-shld-gas.s</c>
    </fragment>

    <target name="KeccakWidth1600Reference" inherits="keccak reference1600"/>
    <target name="KeccakWidth1600Reference32BI" inherits="keccak reference32BI"/>
    <target name="KeccakWidth1600Optimized64" inherits="keccak optimized64"/>
    <target name="KeccakWidth1600Inplace32BI" inherits="keccak inplace32BI"/>
    <target name="KeccakWidth1600Compact64" inherits="keccak compact64"/>
    <target name="KeccakWidth1600Asmx86-64" inherits="keccak asmx86-64"/>
    <target name="KeccakWidth1600Asmx86-64-shld" inherits="keccak asmx86-64-shld"/>

    <!-- Keccak[r+c=800] -->

    <fragment name="width800">
        <h>KeccakF-800/KeccakF-800-interface.h</h>
    </fragment>

    <fragment name="reference800" inherits="common width800">
        <c>KeccakF-800/Reference/KeccakF-800-reference.c</c>
        <c>SnP/SnP-FBWL-default.c</c>
        <c>Tests/displayIntermediateValues.c</c>
        <h>KeccakF-800/Reference/KeccakF-reference.h</h>
        <h>KeccakF-800/Reference/SnP-interface.h</h>
        <h>SnP/SnP-FBWL-default.h</h>
        <h>Tests/displayIntermediateValues.h</h>
        <gcc>-DKeccakReference</gcc>
        <gcc>-O</gcc>
    </fragment>

    <target name="KeccakWidth800Reference" inherits="keccak reference800"/>

    <!-- Keccak[r+c=400] -->

    <fragment name="width400">
        <h>KeccakF-400/KeccakF-400-interface.h</h>
    </fragment>

    <fragment name="reference400" inherits="common width400">
        <c>KeccakF-400/Reference/KeccakF-400-reference.c</c>
        <c>SnP/SnP-FBWL-default.c</c>
        <c>Tests/displayIntermediateValues.c</c>
        <h>KeccakF-400/Reference/KeccakF-reference.h</h>
        <h>KeccakF-400/Reference/SnP-interface.h</h>
        <h>SnP/SnP-FBWL-default.h</h>
        <h>Tests/displayIntermediateValues.h</h>
        <gcc>-DKeccakReference</gcc>
        <gcc>-O</gcc>
    </fragment>

    <target name="KeccakWidth400Reference" inherits="keccak reference400"/>

    <!-- Keccak[r+c=200] -->

    <fragment name="width200">
        <h>KeccakF-200/KeccakF-200-interface.h</h>
    </fragment>

    <fragment name="reference200" inherits="common width200">
        <c>KeccakF-200/Reference/KeccakF-200-reference.c</c>
        <c>SnP/SnP-FBWL-default.c</c>
        <c>Tests/displayIntermediateValues.c</c>
        <h>KeccakF-200/Reference/KeccakF-reference.h</h>
        <h>KeccakF-200/Reference/SnP-interface.h</h>
        <h>SnP/SnP-FBWL-default.h</h>
        <h>Tests/displayIntermediateValues.h</h>
        <gcc>-DKeccakReference</gcc>
        <gcc>-O</gcc>
    </fragment>

    <target name="KeccakWidth200Reference" inherits="keccak reference200"/>

</build>
