name: Run Unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Compile and run unit tests
        run: |
          make generic64/UnitTests
#          cd bin/generic64
#          ./UnitTests -p
