name: Run Unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: sudo apt-get install -y xsltproc

      - name: Compile Unit Tests
        run: make generic64/UnitTests

      - name: Run Unit Tests
        run: bin/generic64/UnitTests -a