name: Run Unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Compile Unit Tests
        run: make generic64/UnitTests

      - name: Change to bin/generic64 directory
        run: cd bin/generic64

      - name: Run Unit Tests
        run: ./UnitTests -a
